import argparse
import csv
import pandas as pd
from pathlib import Path
import numpy as np

OLD_ML_DIR = Path(__file__).parent.parent.parent / "data" / "datasets" / "entervene_current_data_ml_optimized"
NEW_EXTRACTED_DIR = Path(__file__).parent.parent.parent / "data" / "datasets" / "new_extracted_pack"
COMBINED_ML_DIR = Path(__file__).parent.parent.parent / "data" / "datasets" / "entervene_combined_ml_pack"


def build_training_dataset():
    COMBINED_ML_DIR.mkdir(parents=True, exist_ok=True)
    
    # Load new period grades
    pg_path = NEW_EXTRACTED_DIR / "student_period_grades.csv"
    if not pg_path.exists():
        print(f"Error: {pg_path} not found.")
        return
        
    df_new = pd.read_csv(pg_path)
    
    # Sort by student, subject, year, period
    df_new = df_new.sort_values(by=["student_id", "subject", "school_year", "period_sequence"]).reset_index(drop=True)
    
    ml_rows = []
    
    # Group to compute cumulative averages, trends, and target
    grouped = df_new.groupby(["student_id", "subject", "school_year"])
    
    for _, group in grouped:
        periods = group["period_sequence"].tolist()
        grades = group["source_period_grade"].tolist()
        ww = group["written_work_percent"].tolist()
        pt = group["performance_task_percent"].tolist()
        qa = group["quarterly_assessment_percent"].tolist()
        grade_levels = group["grade_level"].tolist()
        
        cumulative_sum = 0.0
        
        for i in range(len(periods)):
            p_seq = periods[i]
            source_grade = grades[i]
            
            # Trend and cumulative
            has_prev = 1 if i > 0 else 0
            prev_grade = grades[i-1] if i > 0 else source_grade
            trend = source_grade - prev_grade
            
            cumulative_sum += source_grade
            cum_avg = cumulative_sum / (i + 1)
            
            # The target is the NEXT period's grade in the same group, if it exists
            if i + 1 < len(periods):
                target_grade = grades[i+1]
                
                row = {
                    "student_id": group["student_id"].iloc[0],
                    "grade_level": grade_levels[i],
                    "period_sequence": p_seq,
                    "has_previous_period": has_prev,
                    "written_work_percent": ww[i] if not pd.isna(ww[i]) else 0,
                    "performance_task_percent": pt[i] if not pd.isna(pt[i]) else 0,
                    "quarterly_assessment_percent": qa[i] if not pd.isna(qa[i]) else 0,
                    "assessment_completion_rate": 1.0,  # Assumption for extracted data
                    "source_period_grade": source_grade,
                    "grade_trend_vs_previous_period": trend,
                    "cumulative_period_grade_avg": cum_avg,
                    "target_next_period_grade": target_grade
                }
                
                # Subject one-hot
                subject = str(group["subject"].iloc[0]).upper().replace(" ", "_")
                row[f"subject_{subject}"] = 1
                
                ml_rows.append(row)
                
    df_ml_new = pd.DataFrame(ml_rows)
    df_ml_new = df_ml_new.fillna(0) # For subject one-hots
    
    # Load old data
    old_train = pd.read_csv(OLD_ML_DIR / "03_random_forest_regression_train.csv")
    old_test = pd.read_csv(OLD_ML_DIR / "04_random_forest_regression_test.csv")
    df_old = pd.concat([old_train, old_test], ignore_index=True)
    
    # Remove synthetic_student_id logic for old df if it exists, ensure student_id matches
    if "synthetic_student_id" in df_old.columns:
        df_old["student_id"] = df_old["synthetic_student_id"]
    
    # Ensure all columns exist in both dataframes (fill missing one-hots with 0)
    all_columns = set(df_old.columns).union(set(df_ml_new.columns))
    
    for col in all_columns:
        if col not in df_old.columns and col.startswith("subject_"):
            df_old[col] = 0
        if col not in df_ml_new.columns and col.startswith("subject_"):
            df_ml_new[col] = 0
            
    # Combine
    combined = pd.concat([df_old, df_ml_new], ignore_index=True)
    
    # Re-fill NaNs generated by concat
    for col in combined.columns:
        if col.startswith("subject_") or col in ["has_previous_period", "written_work_percent"]:
            combined[col] = combined[col].fillna(0)
            
    # Split train/test (80/20) by student_id to avoid data leakage
    unique_students = combined["student_id"].unique()
    np.random.seed(42)
    np.random.shuffle(unique_students)
    
    split_idx = int(len(unique_students) * 0.8)
    train_students = unique_students[:split_idx]
    
    train_df = combined[combined["student_id"].isin(train_students)]
    test_df = combined[~combined["student_id"].isin(train_students)]
    
    # Keep only columns that make sense for the model
    # Drop columns not needed
    drop_cols = ["split", "row_id", "synthetic_student_id", "source_student_id"]
    for c in drop_cols:
        if c in train_df.columns: train_df = train_df.drop(columns=[c])
        if c in test_df.columns: test_df = test_df.drop(columns=[c])
    
    train_path = COMBINED_ML_DIR / "03_random_forest_regression_train.csv"
    test_path = COMBINED_ML_DIR / "04_random_forest_regression_test.csv"
    
    train_df.to_csv(train_path, index=False)
    test_df.to_csv(test_path, index=False)
    
    print(f"Combined data saved to {COMBINED_ML_DIR}")
    print(f"Total training rows: {len(train_df)}")
    print(f"Total test rows: {len(test_df)}")
    print(f"Target below 75 in train: {len(train_df[train_df['target_next_period_grade'] < 75])}")
    print(f"Target below 75 in test: {len(test_df[test_df['target_next_period_grade'] < 75])}")

if __name__ == "__main__":
    build_training_dataset()
