from .AcademicYear   import AcademicYear
from .AcademicPeriod import AcademicPeriod
from .AcademicLevel  import AcademicLevel
from .Subject        import Subject
from .SubjectOffering import SubjectOffering
from .GradingTemplate import GradingTemplate
from .GradingTemplateComponent import GradingTemplateComponent
from .Class_         import Class
from .SubjectLoad    import SubjectLoad
from .StudentCLass   import StudentClass
from .Lesson         import Lesson
from .LessonAssignment import LessonAssignment
from .LessonAttachment import LessonAttachment
from .AssessmentItem import AssessmentItem
from .StudentAssessmentScore import StudentAssessmentScore
from .StudentPeriodGrade import StudentPeriodGrade
