"""Add LessonPlanModel

Revision ID: 12aa5108d9e8
Revises: 20260701_allow_late_submissions
Create Date: 2026-07-27 17:48:38.776548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12aa5108d9e8'
down_revision: Union[str, Sequence[str], None] = '20260701_allow_late_submissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('learning_area', sa.String(length=255), nullable=True),
    sa.Column('grade_section', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('sessions', sa.String(length=255), nullable=True),
    sa.Column('references', sa.String(length=1000), nullable=True),
    sa.Column('ai_declaration', sa.String(length=1000), nullable=True),
    sa.Column('intentions', sa.JSON(), nullable=True),
    sa.Column('learning_experience', sa.JSON(), nullable=True),
    sa.Column('assessment', sa.JSON(), nullable=True),
    sa.Column('ways_forward', sa.JSON(), nullable=True),
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['academic_staff.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.drop_index('idx_classwork_allowed_types_classwork', table_name='classwork_allowed_file_type')
    op.drop_table('classwork_allowed_file_type')
    op.drop_index('idx_academic_level_grade', table_name='academic_level')
    op.drop_index('idx_academic_level_name', table_name='academic_level')
    op.drop_index('idx_academic_period_dates', table_name='academic_period')
    op.drop_index('idx_academic_period_year_active', table_name='academic_period')
    op.drop_index('idx_academic_staff_email', table_name='academic_staff')
    op.drop_index('idx_academic_staff_names', table_name='academic_staff')
    op.drop_index('idx_academic_staff_user_id', table_name='academic_staff')
    op.drop_index('idx_academic_year_active', table_name='academic_year', postgresql_where='(is_active = true)')
    op.drop_index('idx_class_academic_level', table_name='class')
    op.drop_index('idx_class_academic_period', table_name='class')
    op.drop_index('idx_class_academic_year', table_name='class')
    op.drop_index('idx_class_adviser', table_name='class')
    op.drop_index('idx_class_status', table_name='class')
    op.drop_index('idx_class_year_level', table_name='class')
    op.drop_index('idx_classwork_cloned_from', table_name='classwork')
    op.drop_index('idx_classwork_created_by', table_name='classwork')
    op.drop_index('idx_classwork_published', table_name='classwork', postgresql_where='(is_published = true)')
    op.drop_index('idx_classwork_subject', table_name='classwork')
    op.drop_index('idx_classwork_type_category', table_name='classwork')
    op.drop_constraint('classwork_cloned_from_classwork_id_fkey', 'classwork', type_='foreignkey')
    op.drop_column('classwork', 'cloned_from_classwork_id')
    op.drop_column('classwork', 'rubric_id')
    op.drop_constraint('classwork_assignment_classwork_id_class_id_key', 'classwork_assignment', type_='unique')
    op.drop_index('idx_classwork_assignment_assigned_by', table_name='classwork_assignment')
    op.drop_index('idx_classwork_assignment_class', table_name='classwork_assignment')
    op.drop_index('idx_classwork_assignment_classwork', table_name='classwork_assignment')
    op.drop_index('idx_classwork_assignment_dates', table_name='classwork_assignment')
    op.drop_index('idx_classwork_assignment_published', table_name='classwork_assignment')
    op.create_unique_constraint('uq_classwork_assignment', 'classwork_assignment', ['classwork_id', 'class_id'])
    op.drop_index('idx_classwork_attachment_classwork', table_name='classwork_attachment')
    op.drop_index('idx_classwork_attachment_uploaded', table_name='classwork_attachment')
    op.drop_index('idx_classwork_lesson_classwork', table_name='classwork_lesson')
    op.drop_index('idx_classwork_lesson_lesson', table_name='classwork_lesson')
    op.alter_column('lesson', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('lesson', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('lesson', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('lesson', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_lesson_created_by', table_name='lesson')
    op.drop_index('idx_lesson_draft', table_name='lesson', postgresql_where='(is_draft = true)')
    op.drop_index('idx_lesson_order', table_name='lesson')
    op.drop_index('idx_lesson_published', table_name='lesson', postgresql_where='(is_published = true)')
    op.drop_index('idx_lesson_subject', table_name='lesson')
    op.drop_index('idx_lesson_assignment_assigned_by', table_name='lesson_assignment')
    op.drop_index('idx_lesson_assignment_class', table_name='lesson_assignment')
    op.drop_index('idx_lesson_assignment_lesson', table_name='lesson_assignment')
    op.drop_index('idx_lesson_assignment_published', table_name='lesson_assignment')
    op.drop_constraint('lesson_assignment_lesson_id_class_id_key', 'lesson_assignment', type_='unique')
    op.create_unique_constraint('uq_lesson_assignment', 'lesson_assignment', ['lesson_id', 'class_id'])
    op.drop_index('idx_lesson_attachment_lesson', table_name='lesson_attachment')
    op.drop_index('idx_lesson_attachment_uploaded', table_name='lesson_attachment')
    op.drop_index('ix_question_lesson_id', table_name='question')
    op.drop_index('ix_question_question_type', table_name='question')
    op.drop_index('ix_question_option_question_id', table_name='question_option')
    op.drop_index('ix_quiz_classwork_id', table_name='quiz')
    op.drop_index('ix_quiz_answer_quiz_question_id', table_name='quiz_answer')
    op.drop_index('ix_quiz_answer_submission_id', table_name='quiz_answer')
    op.drop_index('ix_quiz_question_question_id', table_name='quiz_question')
    op.drop_index('ix_quiz_question_quiz_id', table_name='quiz_question')
    op.drop_index('ix_quiz_setting_classwork_id', table_name='quiz_setting')
    op.drop_constraint('role_role_name_key', 'role', type_='unique')
    op.alter_column('student', 'student_lrn',
               existing_type=sa.CHAR(length=12),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.drop_index('idx_student_academic_level', table_name='student')
    op.drop_index('idx_student_account_status', table_name='student')
    op.drop_index('idx_student_email', table_name='student')
    op.drop_index('idx_student_lrn', table_name='student')
    op.drop_index('idx_student_names', table_name='student')
    op.drop_index('idx_student_user_id', table_name='student')
    op.drop_constraint('student_academic_level_id_fkey', 'student', type_='foreignkey')
    op.drop_column('student', 'import_log_id')
    op.drop_column('student', 'guardian_id')
    op.drop_column('student', 'created_at')
    op.drop_column('student', 'account_status')
    op.drop_index('idx_student_class_class', table_name='student_class')
    op.drop_index('idx_student_class_enrolled', table_name='student_class')
    op.drop_index('idx_student_class_status', table_name='student_class')
    op.drop_index('idx_student_class_student', table_name='student_class')
    op.drop_constraint('student_class_student_id_class_id_key', 'student_class', type_='unique')
    op.create_unique_constraint('uq_student_class', 'student_class', ['student_id', 'class_id'])
    op.drop_constraint('student_class_student_id_fkey', 'student_class', type_='foreignkey')
    op.create_foreign_key(None, 'student_class', 'student', ['student_id'], ['student_id'])
    op.drop_index('idx_student_submission_assignment', table_name='student_submission')
    op.drop_index('idx_student_submission_graded_by', table_name='student_submission')
    op.drop_index('idx_student_submission_status', table_name='student_submission')
    op.drop_index('idx_student_submission_student', table_name='student_submission')
    op.drop_index('idx_student_submission_student_assignment', table_name='student_submission')
    op.drop_index('idx_student_submission_submitted', table_name='student_submission')
    op.drop_index('idx_subject_academic_level', table_name='subject')
    op.drop_index('idx_subject_codename', table_name='subject')
    op.drop_index('idx_subject_status', table_name='subject')
    op.drop_index('idx_subject_load_class', table_name='subject_load')
    op.drop_index('idx_subject_load_continued', table_name='subject_load')
    op.drop_index('idx_subject_load_period', table_name='subject_load')
    op.drop_index('idx_subject_load_staff', table_name='subject_load')
    op.drop_index('idx_subject_load_status', table_name='subject_load')
    op.drop_index('idx_subject_load_subject', table_name='subject_load')
    op.drop_constraint('subject_load_staff_id_subject_id_class_id_academic_period_i_key', 'subject_load', type_='unique')
    op.create_unique_constraint('uq_subject_load', 'subject_load', ['staff_id', 'subject_id', 'class_id', 'academic_period_id'])
    op.drop_index('idx_submission_attachment_submission', table_name='submission_attachment')
    op.drop_index('idx_submission_attachment_uploaded', table_name='submission_attachment')
    op.drop_index('ix_suggestion_classwork_assignment_id', table_name='suggestion_classwork')
    op.drop_index('idx_user_account_email', table_name='user_account')
    op.drop_index('idx_user_account_ref', table_name='user_account')
    op.drop_index('idx_user_account_status', table_name='user_account')
    op.alter_column('user_login_log', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_login_log', 'login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_user_login_log_login_at', table_name='user_login_log')
    op.drop_index('idx_user_login_log_logout', table_name='user_login_log', postgresql_where='(logout_at IS NOT NULL)')
    op.drop_index('idx_user_login_log_user', table_name='user_login_log')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_login_log_user', 'user_login_log', ['user_id'], unique=False)
    op.create_index('idx_user_login_log_logout', 'user_login_log', ['logout_at'], unique=False, postgresql_where='(logout_at IS NOT NULL)')
    op.create_index('idx_user_login_log_login_at', 'user_login_log', ['login_at'], unique=False)
    op.alter_column('user_login_log', 'login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_login_log', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_user_account_status', 'user_account', ['account_status'], unique=False)
    op.create_index('idx_user_account_ref', 'user_account', ['ref_type', 'ref_id'], unique=False)
    op.create_index('idx_user_account_email', 'user_account', ['email'], unique=False)
    op.create_index('ix_suggestion_classwork_assignment_id', 'suggestion_classwork', ['classwork_assignment_id'], unique=False)
    op.create_index('idx_submission_attachment_uploaded', 'submission_attachment', ['uploaded_at'], unique=False)
    op.create_index('idx_submission_attachment_submission', 'submission_attachment', ['submission_id'], unique=False)
    op.drop_constraint('uq_subject_load', 'subject_load', type_='unique')
    op.create_unique_constraint('subject_load_staff_id_subject_id_class_id_academic_period_i_key', 'subject_load', ['staff_id', 'subject_id', 'class_id', 'academic_period_id'])
    op.create_index('idx_subject_load_subject', 'subject_load', ['subject_id'], unique=False)
    op.create_index('idx_subject_load_status', 'subject_load', ['status'], unique=False)
    op.create_index('idx_subject_load_staff', 'subject_load', ['staff_id'], unique=False)
    op.create_index('idx_subject_load_period', 'subject_load', ['academic_period_id'], unique=False)
    op.create_index('idx_subject_load_continued', 'subject_load', ['continued_from_load_id'], unique=False)
    op.create_index('idx_subject_load_class', 'subject_load', ['class_id'], unique=False)
    op.create_index('idx_subject_status', 'subject', ['status'], unique=False)
    op.create_index('idx_subject_codename', 'subject', ['subject_codename'], unique=False)
    op.create_index('idx_subject_academic_level', 'subject', ['academic_level_id'], unique=False)
    op.create_index('idx_student_submission_submitted', 'student_submission', ['submitted_at'], unique=False)
    op.create_index('idx_student_submission_student_assignment', 'student_submission', ['student_id', 'classwork_assignment_id'], unique=False)
    op.create_index('idx_student_submission_student', 'student_submission', ['student_id'], unique=False)
    op.create_index('idx_student_submission_status', 'student_submission', ['status'], unique=False)
    op.create_index('idx_student_submission_graded_by', 'student_submission', ['graded_by_staff_id'], unique=False)
    op.create_index('idx_student_submission_assignment', 'student_submission', ['classwork_assignment_id'], unique=False)
    op.drop_constraint(None, 'student_class', type_='foreignkey')
    op.create_foreign_key('student_class_student_id_fkey', 'student_class', 'student', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.drop_constraint('uq_student_class', 'student_class', type_='unique')
    op.create_unique_constraint('student_class_student_id_class_id_key', 'student_class', ['student_id', 'class_id'])
    op.create_index('idx_student_class_student', 'student_class', ['student_id'], unique=False)
    op.create_index('idx_student_class_status', 'student_class', ['enrollment_status'], unique=False)
    op.create_index('idx_student_class_enrolled', 'student_class', ['enrolled_at'], unique=False)
    op.create_index('idx_student_class_class', 'student_class', ['class_id'], unique=False)
    op.add_column('student', sa.Column('account_status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('guardian_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('import_log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('student_academic_level_id_fkey', 'student', 'academic_level', ['academic_level_id'], ['academic_level_id'])
    op.create_index('idx_student_user_id', 'student', ['user_id'], unique=False)
    op.create_index('idx_student_names', 'student', ['last_name', 'first_name', 'middle_name'], unique=False)
    op.create_index('idx_student_lrn', 'student', ['student_lrn'], unique=False)
    op.create_index('idx_student_email', 'student', ['email'], unique=False)
    op.create_index('idx_student_account_status', 'student', ['account_status'], unique=False)
    op.create_index('idx_student_academic_level', 'student', ['academic_level_id'], unique=False)
    op.alter_column('student', 'student_lrn',
               existing_type=sa.String(length=12),
               type_=sa.CHAR(length=12),
               existing_nullable=False)
    op.create_unique_constraint('role_role_name_key', 'role', ['role_name'])
    op.create_index('ix_quiz_setting_classwork_id', 'quiz_setting', ['classwork_id'], unique=False)
    op.create_index('ix_quiz_question_quiz_id', 'quiz_question', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_question_question_id', 'quiz_question', ['question_id'], unique=False)
    op.create_index('ix_quiz_answer_submission_id', 'quiz_answer', ['submission_id'], unique=False)
    op.create_index('ix_quiz_answer_quiz_question_id', 'quiz_answer', ['quiz_question_id'], unique=False)
    op.create_index('ix_quiz_classwork_id', 'quiz', ['classwork_id'], unique=False)
    op.create_index('ix_question_option_question_id', 'question_option', ['question_id'], unique=False)
    op.create_index('ix_question_question_type', 'question', ['question_type'], unique=False)
    op.create_index('ix_question_lesson_id', 'question', ['lesson_id'], unique=False)
    op.create_index('idx_lesson_attachment_uploaded', 'lesson_attachment', ['uploaded_at'], unique=False)
    op.create_index('idx_lesson_attachment_lesson', 'lesson_attachment', ['lesson_id'], unique=False)
    op.drop_constraint('uq_lesson_assignment', 'lesson_assignment', type_='unique')
    op.create_unique_constraint('lesson_assignment_lesson_id_class_id_key', 'lesson_assignment', ['lesson_id', 'class_id'])
    op.create_index('idx_lesson_assignment_published', 'lesson_assignment', ['is_published', 'publish_date'], unique=False)
    op.create_index('idx_lesson_assignment_lesson', 'lesson_assignment', ['lesson_id'], unique=False)
    op.create_index('idx_lesson_assignment_class', 'lesson_assignment', ['class_id'], unique=False)
    op.create_index('idx_lesson_assignment_assigned_by', 'lesson_assignment', ['assigned_by_staff_id'], unique=False)
    op.create_index('idx_lesson_subject', 'lesson', ['subject_id'], unique=False)
    op.create_index('idx_lesson_published', 'lesson', ['is_published'], unique=False, postgresql_where='(is_published = true)')
    op.create_index('idx_lesson_order', 'lesson', ['subject_id', 'order_index'], unique=False)
    op.create_index('idx_lesson_draft', 'lesson', ['is_draft'], unique=False, postgresql_where='(is_draft = true)')
    op.create_index('idx_lesson_created_by', 'lesson', ['created_by_staff_id'], unique=False)
    op.alter_column('lesson', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('lesson', 'is_draft',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('lesson', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('lesson', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index('idx_classwork_lesson_lesson', 'classwork_lesson', ['lesson_id'], unique=False)
    op.create_index('idx_classwork_lesson_classwork', 'classwork_lesson', ['classwork_id'], unique=False)
    op.create_index('idx_classwork_attachment_uploaded', 'classwork_attachment', ['uploaded_at'], unique=False)
    op.create_index('idx_classwork_attachment_classwork', 'classwork_attachment', ['classwork_id'], unique=False)
    op.drop_constraint('uq_classwork_assignment', 'classwork_assignment', type_='unique')
    op.create_index('idx_classwork_assignment_published', 'classwork_assignment', ['is_published', 'publish_date'], unique=False)
    op.create_index('idx_classwork_assignment_dates', 'classwork_assignment', ['publish_date', 'due_date', 'lock_date'], unique=False)
    op.create_index('idx_classwork_assignment_classwork', 'classwork_assignment', ['classwork_id'], unique=False)
    op.create_index('idx_classwork_assignment_class', 'classwork_assignment', ['class_id'], unique=False)
    op.create_index('idx_classwork_assignment_assigned_by', 'classwork_assignment', ['assigned_by_staff_id'], unique=False)
    op.create_unique_constraint('classwork_assignment_classwork_id_class_id_key', 'classwork_assignment', ['classwork_id', 'class_id'])
    op.add_column('classwork', sa.Column('rubric_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('classwork', sa.Column('cloned_from_classwork_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('classwork_cloned_from_classwork_id_fkey', 'classwork', 'classwork', ['cloned_from_classwork_id'], ['classwork_id'])
    op.create_index('idx_classwork_type_category', 'classwork', ['classwork_type', 'classwork_category'], unique=False)
    op.create_index('idx_classwork_subject', 'classwork', ['subject_id'], unique=False)
    op.create_index('idx_classwork_published', 'classwork', ['is_published'], unique=False, postgresql_where='(is_published = true)')
    op.create_index('idx_classwork_created_by', 'classwork', ['created_by_staff_id'], unique=False)
    op.create_index('idx_classwork_cloned_from', 'classwork', ['cloned_from_classwork_id'], unique=False)
    op.create_index('idx_class_year_level', 'class', ['academic_year_id', 'academic_level_id'], unique=False)
    op.create_index('idx_class_status', 'class', ['class_status'], unique=False)
    op.create_index('idx_class_adviser', 'class', ['adviser_staff_id'], unique=False)
    op.create_index('idx_class_academic_year', 'class', ['academic_year_id'], unique=False)
    op.create_index('idx_class_academic_period', 'class', ['academic_period_id'], unique=False)
    op.create_index('idx_class_academic_level', 'class', ['academic_level_id'], unique=False)
    op.create_index('idx_academic_year_active', 'academic_year', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_academic_staff_user_id', 'academic_staff', ['user_id'], unique=False)
    op.create_index('idx_academic_staff_names', 'academic_staff', ['last_name', 'first_name'], unique=False)
    op.create_index('idx_academic_staff_email', 'academic_staff', ['email'], unique=False)
    op.create_index('idx_academic_period_year_active', 'academic_period', ['academic_year_id', 'is_active'], unique=False)
    op.create_index('idx_academic_period_dates', 'academic_period', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_academic_level_name', 'academic_level', ['level_name'], unique=False)
    op.create_index('idx_academic_level_grade', 'academic_level', ['grade_level'], unique=True)
    op.create_table('classwork_allowed_file_type',
    sa.Column('allowed_type_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('classwork_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_type_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('extensions', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classwork_id'], ['classwork.classwork_id'], name='classwork_allowed_file_type_classwork_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allowed_type_id', name='classwork_allowed_file_type_pkey')
    )
    op.create_index('idx_classwork_allowed_types_classwork', 'classwork_allowed_file_type', ['classwork_id'], unique=False)
    op.drop_table('lesson_plan')
    # ### end Alembic commands ###
