"""add_attendance_and_leave_request_tables

Revision ID: 22b964f8c2e2
Revises: 20260812_drop_legacy_pathway_string_columns
Create Date: 2026-08-13 02:23:39.329170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b964f8c2e2'
down_revision: Union[str, Sequence[str], None] = '20260812_drop_legacy_pathway_string_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_record',
    sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by_staff_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_staff_id'], ['academic_staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('student_id', 'class_id', 'date', name='uq_attendance_student_class_date')
    )
    op.create_index(op.f('ix_attendance_record_class_id'), 'attendance_record', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_date'), 'attendance_record', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_record_student_id'), 'attendance_record', ['student_id'], unique=False)
    op.create_table('leave_request',
    sa.Column('leave_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_staff_id', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_staff_id'], ['academic_staff.staff_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leave_request_id')
    )
    op.create_index(op.f('ix_leave_request_class_id'), 'leave_request', ['class_id'], unique=False)
    op.create_index(op.f('ix_leave_request_student_id'), 'leave_request', ['student_id'], unique=False)
    op.alter_column('subject', 'subject_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'subject_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_leave_request_student_id'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_class_id'), table_name='leave_request')
    op.drop_table('leave_request')
    op.drop_index(op.f('ix_attendance_record_student_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_date'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_class_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    # ### end Alembic commands ###
