"""add subject load versioning

Revision ID: 27ae3176cae2
Revises: 572462a5b498
Create Date: 2026-08-02 13:41:50.162334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ae3176cae2'
down_revision: Union[str, Sequence[str], None] = '572462a5b498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    subj_cols = [c['name'] for c in inspector.get_columns('subject')]
    if 'is_math_or_science' not in subj_cols:
        op.add_column('subject', sa.Column('is_math_or_science', sa.Boolean(), nullable=True))

    subj_acad_col = next((c for c in inspector.get_columns('subject') if c['name'] == 'academic_level_id'), None)
    if subj_acad_col and not subj_acad_col.get('nullable'):
        op.alter_column('subject', 'academic_level_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)

    sl_cols = [c['name'] for c in inspector.get_columns('subject_load')]
    if 'version' not in sl_cols:
        op.add_column('subject_load', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    if 'is_active_version' not in sl_cols:
        op.add_column('subject_load', sa.Column('is_active_version', sa.Boolean(), nullable=False, server_default='true'))
    if 'published_at' not in sl_cols:
        op.add_column('subject_load', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    if 'published_by' not in sl_cols:
        op.add_column('subject_load', sa.Column('published_by', sa.String(length=50), nullable=True))
    if 'last_modified_by' not in sl_cols:
        op.add_column('subject_load', sa.Column('last_modified_by', sa.String(length=50), nullable=True))
    if 'draft_notes' not in sl_cols:
        op.add_column('subject_load', sa.Column('draft_notes', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_load', 'draft_notes')
    op.drop_column('subject_load', 'last_modified_by')
    op.drop_column('subject_load', 'published_by')
    op.drop_column('subject_load', 'published_at')
    op.drop_column('subject_load', 'is_active_version')
    op.drop_column('subject_load', 'version')
    op.alter_column('subject', 'academic_level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subject', 'is_math_or_science')
    # ### end Alembic commands ###
