"""add_notification_table

Revision ID: 844db2477657
Revises: d31025bd1360
Create Date: 2026-08-10 21:59:20.931874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844db2477657'
down_revision: Union[str, Sequence[str], None] = 'd31025bd1360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.drop_table('period_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_template',
    sa.Column('template_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_group', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('duration_mins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_break', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('template_id', name='period_template_pkey')
    )
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
