"""add_setting_table

Revision ID: ea616545b5c4
Revises: b57b02a3f427
Create Date: 2026-07-28 12:03:05.665163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea616545b5c4'
down_revision: Union[str, Sequence[str], None] = 'b57b02a3f427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('STRING', 'BOOLEAN', 'INTEGER', 'JSON', name='setting_type_enum'), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=True)
    op.create_table('lesson_plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('learning_area', sa.String(length=255), nullable=True),
    sa.Column('grade_section', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('sessions', sa.String(length=255), nullable=True),
    sa.Column('references', sa.String(length=1000), nullable=True),
    sa.Column('ai_declaration', sa.String(length=1000), nullable=True),
    sa.Column('intentions', sa.JSON(), nullable=True),
    sa.Column('learning_experience', sa.JSON(), nullable=True),
    sa.Column('assessment', sa.JSON(), nullable=True),
    sa.Column('ways_forward', sa.JSON(), nullable=True),
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['academic_staff.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_plan')
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_table('setting')
    # ### end Alembic commands ###
