"""add start_time end_time days_of_week to subject_load

Revision ID: fe064f391d28
Revises: 20260728_add_activity_mode
Create Date: 2026-07-29 03:30:34.089383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe064f391d28'
down_revision: Union[str, Sequence[str], None] = '20260728_add_activity_mode'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_load', sa.Column('start_time', sa.String(length=10), nullable=True))
    op.add_column('subject_load', sa.Column('end_time', sa.String(length=10), nullable=True))
    op.add_column('subject_load', sa.Column('days_of_week', sa.JSON(), nullable=True))
    op.alter_column('subject_load', 'staff_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('uq_subject_load', 'subject_load', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subject_load', 'subject_load', ['staff_id', 'subject_id', 'class_id', 'academic_period_id'])
    op.alter_column('subject_load', 'staff_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('subject_load', 'days_of_week')
    op.drop_column('subject_load', 'end_time')
    op.drop_column('subject_load', 'start_time')
    # ### end Alembic commands ###
